### ISSUE TITLE
文字错误

### ISSUE THREAD

**Issue by SuoHouDaiShi** [CSneko/toNeko#1]
![图片](https://github.com/CSneko/toNeko/assets/119282947/2ee78c3a-8d17-4413-a701-ef3f792ebcb5)
![图片](https://github.com/CSneko/toNeko/assets/119282947/ae12f2d2-1d63-42e0-9999-df18fc670316)
应该将“厥”替换为“撅”

**Comment by CSneko** [comment]
其实我已经注意到了这个问题，但是由于我电脑一直打不出"撅"这个字，就暂时用的"厥"替代，不过也是感谢提醒

**Comment by SuoHouDaiShi** [comment]
@CSneko PR请求我发了，你合并以后发下release吧（）

**Comment by CSneko** [comment]
就两个撅字没必要发PR[]，因为我已经在你发PR前就在本地将其改正了

**Comment by SuoHouDaiShi** [comment]
> 就两个撅字没必要发PR[]，因为我已经在你发PR前就在本地将其改正了

OK（
那我close了先，记得发release（
