### ISSUE TITLE
[bug]插件与部分客户端优化mod不兼容

### ISSUE THREAD

**Issue by xiaole2999** [CSneko/toNeko#13]
客户端复现环境：System Info: Java 20 (Java HotSpot(TM) 64-Bit Server VM 20.0.1+9-29) Host: Windows 11 10.0 (amd64)
服务端复现环境：Java 19 (Java HotSpot(TM) 64-Bit Server VM 19.0.2+7-44) Host: Linux 6.1.0-11-amd64 (amd64)
服务器核心：fabric-server-mc.1.20.2-loader.0.15.2-launcher.0.11.2.jar
复现操作：安装最新版本ctlib,toneko,登录服务器即可复现
具体描述：
![image](https://github.com/CSneko/toNeko/assets/85883077/dde20e3a-36fa-4912-992b-06915355c165)
没有安装任何mod时，无此问题，可正常登录和聊天，安装优化mod会出现此问题
客户端整合包：Fabulously Optimized 5.6.3 for 1.20.2 （只有优化mod，没有功能性mod）
插件版本：toNeko-0.1.2，ctLib0.0.11

**Comment by CSneko** [comment]
先尝试删除所有有关聊天的mod,后面我会寻找其它解决方案

**Comment by xiaole2999** [comment]
> 先尝试删除所有有关聊天的mod,后面我会寻找其它解决方案

![image](https://github.com/CSneko/toNeko/assets/85883077/d98023cd-74e8-4217-97ed-7a1455fcc00f)
就剩下这两个没禁用了...

**Comment by xiaole2999** [comment]
![image](https://github.com/CSneko/toNeko/assets/85883077/b9746f4c-fde8-49a9-a7d1-67595a4b2610)
可能是撅猫棒的问题

**Comment by CSneko** [comment]
这个问题可能与整合包有关系，从这个错误可以看出是无法加载材质（这是个已知问题），它会导致物品无法正常显示材质，但是不至于崩溃，当然也有可能是某些其它的原因，撅猫帮是一个即将被删除的东西，因为它单独做成物品会与Bukkit端的撅猫棒原理不同，等会会发布下一个版本，会尝试修复它

**Comment by xiaole2999** [comment]
> 这个问题可能与整合包有关系，从这个错误可以看出是无法加载材质（这是个已知问题），它会导致物品无法正常显示材质，但是不至于崩溃，当然也有可能是某些其它的原因，撅猫帮是一个即将被删除的东西，因为它单独做成物品会与Bukkit端的撅猫棒原理不同，等会会发布下一个版本，会尝试修复它

在不安装任何mod只安装api的情况下，会报一模一样的错误，好像跟整合包的关系不大

**Comment by CSneko** [comment]
尝试使用最新的预览版，或许能解决该问题

**Comment by xiaole2999** [comment]
> 尝试使用最新的预览版，或许能解决该问题

ok，问题已解决
