### ISSUE TITLE
[bug]聊天信息均以message.toneko.****格式显示

### ISSUE THREAD

**Issue by xiaole2999** [CSneko/toNeko#14]
复现环境：linux和windows均可复现
服务器核心：fabric-server-mc.1.20.2-loader.0.15.2-launcher.0.11.2.jar
复现操作：安装最新版本ctlib,toneko,键入相关指令即可复现
具体描述：
![image](https://github.com/CSneko/toNeko/assets/85883077/1d165fc8-3fcb-4a11-8b30-4e3688dd64a9)
插件版本：toNeko-0.1.3，ctLib0.0.12-pre

**Comment by CSneko** [comment]
客户端需要安装mod
