### ISSUE TITLE
[bug]语言无法更改为中文

### ISSUE THREAD

**Issue by xiaole2999** [CSneko/toNeko#15]
复现环境：所有环境
服务器核心：fabric-server-mc.1.20.2-loader.0.15.2-launcher.0.11.2.jar
复现操作：一直可以被复现
插件版本：ctLibMod-0.0.11,toNekoFabric-0.1.3
具体描述：如题，没有生成任何配置文件可以更改

**Comment by CSneko** [comment]
Fabric mod的语言是根据客户端使用的语言决定，如果该问题频繁出现，我会将其改为服务端决定语言
