### ISSUE TITLE
添加Forge支持

### ISSUE THREAD

**Issue by konsolas-aac** [CSneko/toNeko#16]
因为这个Mod/Plugin无法在Forge上加载，我是否能为其添加Forge支持并更新？

**Comment by CSneko** [comment]
当然可以

**Comment by pltision** [comment]
嗨，我也有在Forge上支持这个mod的意愿喵~ 但我想做的是一个重制版，而不只是迁移这个模组。

请问 @konsolas-aac 是否已经开始制作Forge版了? 如果您已经开始制作了我会放弃这个想法或者等你完成并在你的基础上开发附属模组。

若我进行重制的话由于我可能会对原作进行大幅度更改，甚至使其变在法律意义上可能只会算作一个“借鉴”的模组。我希望在更宽松的 CC 0 许可证下提供模组，如果您对此持强烈反对意见我可以继续遵循GPL许可证发布喵~

此外希望作者能尽快修复新的bug捏，我对服务端不是那么熟悉并且有点懒得去下载一个服务端玩（
也因为我不太懂服务端和fabric，看不太懂你写的代码（懒的动脑），所以才会想重制喵qwq
如果有重制版的话，我会尽力提高它的可扩展性的，相信我的代码能力qwq

**Comment by CSneko** [comment]
@pltision 
这个issues的提出已经有一个月时间了喵，但@konsolas-aac 似乎再github上没有活动喵~

该模组的逻辑并不算复杂，但代码不是很好，因此基于代码进行修改可能不会那么容易喵~ 不过聊天和实体这两部分较为复杂，可能重置不那么简单喵~

如果你现在给予原版修改的话，你可以尝试使用[Forgified Fabric API](https://modrinth.com/mod/forgified-fabric-api)进行简化喵~ 如果你选择重构的话，最好是能够与原版保持相对一致，这样的话较难的聊天部分可以直接复制喵~

我已经将协议更改为较为宽松的MIT喵~

**Comment by pltision** [comment]
我已经在服务器中体验了你的插件~
本模组的逻辑确实并不复杂喵，我认为我可以使用mixin的方法来实现对话修改等类似的功能并尽少对原版的对话修改喵。至于猫娘标记，我可以用Forge的能力系统来实现它。
我认为这个模组的玩法以及功能和命令语法还是不够令我满意的，我会在重制版中对其修改，不能与原版保持一致实在抱歉啦~
那么我现在已经考虑开始制作重制版啦，预计能在两个星期内完成喵~ 我可能不会去兼容Fabric，所以也请你努力维护啦~

**Comment by pltision** [comment]
啊对了，关于联网功能的内容我是肯定不会重制的喵，毕竟我对api一窍不通（
此外上文的猫娘标记指的是记录所属主人和所属猫娘的信息喵

**Comment by CSneko** [comment]
插件其实没有过多涉及到联网---只有AI部分使用到了联网API

对于聊天修改，并不推荐使用mixin，这会导致模组的稳定性和兼容性变低，推荐使用Forge监听事件实现

**Comment by pltision** [comment]
我已经实现了基本功能了，再过两天做好玩法就可以发布了喵~
现在即将为其添加一些玩法，如果你有什么意见的话当然也可以与我讨论喵，项目的链接先贴这了，我开启了discussions功能以便更加随机的提供建议（如果你愿意的话）https://github.com/pltision/toNekoReforged

聊天修改我之前没看，还以为要用mixin喵，不过事件好像是替换原来的文本（还没试），我不太希望直接替换，不过好像用事件也是最优解了吧...? 你的聊天信息的修改规则除了后缀我都可以考虑抄一下喵。

**Comment by pltision** [comment]
模组已经完成并发布到mcmod了喵~ https://www.mcmod.cn/class/13821.html
相比原版：支持多个主人/猫娘、更智能的后缀添加、药水效果获取部分缺失、未联动权限组配置工具也暂未提供接口。
所以这个issues也终于可以done了喵...?

**Comment by CSneko** [comment]
这个issues会保持开启，为了方便其它玩家来寻找Forge版本

如果你不介意，可以在mcmod资料上添加forge版本的链接

如果你的代码有值得参考的地方，我可能会参考你的代码

**Comment by pltision** [comment]
mcmod资料可以添加喵
PetPhrase类可以参考，可选署名喵~

**Comment by konsolas-aac** [comment]
久违了各位，因学业原因未能更新，我个人感到抱歉。
接下来我会和pltision一起尽力更新的喵~
实在抱歉了喵~

**Comment by CSneko** [comment]
新版本已经有官方的NeoForge支持，所以此issues可以被关闭
