### ISSUE TITLE
[feature request]添加取消替换玩家消息格式的设置

### ISSUE THREAD

**Issue by squi2rel** [CSneko/toNeko#18]
将原版消息替换成username >> message格式后控制台不会记录玩家聊天 导致MCDR失效

建议：添加一个设置 或者将原版消息输出到控制台

**Comment by CSneko** [comment]
如果你使用Fabric 可暂时尝试使用
【因为一个称号，服务器的MCDR居然报废了？看这里帮你修复！-哔哩哔哩】 https://b23.tv/bfXp8OB

**Comment by CSneko** [comment]
已添加配置项`chat.enable`，可通过设置为true或false来控制是否启用
