### ISSUE TITLE
1.20.2.启动游戏崩溃

### ISSUE THREAD

**Issue by AutumnWishCN** [CSneko/toNeko#19]
[minecraft-exported-logs-2024-02-02T22-41-42.log](https://github.com/CSneko/toNeko/files/14141775/minecraft-exported-logs-2024-02-02T22-41-42.log)
日志如上
模组：Better_end_rod-0.0.3, ctLibMod-0.0.15, fabric-api-0.91.5+1.20.2, geckolib-fabric-1.20.2-4.3.1, jei, toNeKoMod-0.21， Fabric 1.20.2-0.15.4

**Comment by CSneko** [comment]
该问题会在下一次更新尝试解决，目前的解决方法:
从toneko.jar中复制config.yml到游戏目录(通常是 `启动器目录/.minecraft/versions/游戏版本/`)下的ctlib/toneko文件夹内

**Comment by AutumnWishCN** [comment]
谢谢大大，现在成功了（最后发现ctlib不在versions里，而是直接在.minecraft下）
