### ISSUE TITLE
[bug]聊天报sql问题

### ISSUE THREAD

**Issue by squi2rel** [CSneko/toNeko#21]
![image](https://github.com/CSneko/toNeko/assets/102400902/69b5dfda-2871-4ea4-bdff-1d917bed8455)
每次猫娘发送聊天都会触发

**Comment by CSneko** [comment]
已解决

**Comment by w2w2e2wq** [comment]
再次出现()  org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such column: neko)
