### ISSUE TITLE
[bug]1.20.1无法进入世界

### ISSUE THREAD

**Issue by pltision** [CSneko/toNeko#23]
当创建或进入一个世界时，游戏会崩溃。已尝试在最少模组的环境启动。

- 游戏版本: 1.20.1
- 模组版本: 0.2.6
- Fabric版本: 0.15.6
- Fabric Api版本: 0.91.1
- ctLib版本: 0.0.12
- GeckoLib版本: 4.4.2
[latest.log](https://github.com/CSneko/toNeko/files/14232461/latest.log)

(这个mod怎么这么多奇奇怪怪bug啊喵qwq

**Comment by CSneko** [comment]
将ctlib更新到0.0.15试试

**Comment by pltision** [comment]
啊这个模组也不爱发CurseForge喵....
我尝试在网页下载模组后仍然没法进入世界喵，这可能不是前置插件的问题了...?
或者说我下载的模组仍是错误的，请你帮忙看看吧。
[mods.zip](https://github.com/CSneko/toNeko/files/14235484/mods.zip)
[latest.log](https://github.com/CSneko/toNeko/files/14235485/latest.log)

此外ctLib的版本管理看起来很混乱呀，这是它在启动器里看起来的样子
![image](https://github.com/CSneko/toNeko/assets/110087936/2a2b5268-a9d3-41a7-884e-4b71e21bd3ec)

**Comment by pltision** [comment]
图片似乎出了点问题，我是用win11的画图程序制作的，我在复制是没意识到我框选的只有一个图层喵
![image](https://github.com/CSneko/toNeko/assets/110087936/2a5067f8-5b00-40fa-9345-20f13c6e3a67)

**Comment by CSneko** [comment]
Bug原因已找到，下个版本修复

**Comment by CSneko** [comment]
这个问题是由于从低版本升级到高版本导致的配置文件问题，解决方法：删除`游戏目录/versions/版本/ctlib/toneko/config.yml`即可

因此，该问题可能不会修复

**Comment by CSneko** [comment]
插件端已经添加了自动修复功能，模组端暂时不打算添加(未来的一些版本不会对配置文件进行修改)

**Comment by frost-8816** [comment]
1.20.1无法进入游戏，游戏报错
![a7f507757dbc83bba16bcde2038f488b](https://github.com/user-attachments/assets/f7619684-d59c-4ee3-9c53-dbce35dbfb11)

![2d8557c8e8f39ce0b1f5ff8ac2f187ca](https://github.com/user-attachments/assets/ac44d4b5-fd02-4404-8318-8340bc7727c5)

**Comment by CSneko** [comment]
如果是1.20.1的话....建议不要使用**1.0.0**版本，尝试使用[0.4.6](https://modrinth.com/mod/tonekomod/version/LQ0SsQpV)以及[ctlib0.1.7](https://modrinth.com/mod/ctlibmod/version/0.1.7)
