### ISSUE TITLE
[Bug]红石末地烛耐久为负数

### ISSUE THREAD

**Issue by MCAbleBlank** [CSneko/toNeko#28]
![屏幕截图 2024-03-03 162615](https://github.com/CSneko/toNeko/assets/107293178/6f059fb3-e9cb-40e8-8f7b-81ac5f6dae93)

建议修复红石末地烛耐久可以为负数的Bug，让其在耐久耗尽后消失或损坏。

另外我建议可以把耐久值改为电量值，归零后用一个红石块和损坏的红石末地烛合成一次重新充电。

**Comment by CSneko** [comment]
你发这里干嘛
