### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dyhags** [CSneko/toNeko#38]

**Comment by dyhags** [comment]
似乎发现一个问题,当背包里有许多末地烛时,使用时字幕会很快.
应该不算问题,如果的确不是问题,您就不用回答了,我将关闭,谢谢.

**Comment by CSneko** [comment]
但是你不应该在这里提交MoreEndRod的Bug,那个模组已经停止更新，未来将不会受到任何支持。

**Comment by dyhags** [comment]
感谢.
