### ISSUE TITLE
可否搬运插件到Modrinth？

### ISSUE THREAD

**Issue by SuoHouDaiShi** [CSneko/toNeko#4]
@CSneko 
Modrinth现在成为了主流Minecraft模组/插件网站
我寻思我能不能把你的插件搬到modrinth上（至少目前没有未经许可的上传
![图片](https://github.com/CSneko/toNeko/assets/119282947/ace44d64-f1e7-48bf-9669-1a6d6ae9d0f3)

**Comment by CSneko** [comment]
当然可以，只要你把github的链接展示上去即可

**Comment by SuoHouDaiShi** [comment]
ok

**Comment by SuoHouDaiShi** [comment]
@CSneko Modrinth版主说需要提供en_us的本地化文件，你做一个出来吧……

**Comment by CSneko** [comment]
我已经上传了一个版本在modrinth的mod区(https://modrinth.com/mod/toneko)，因为Fabric版本是有en_us.json的，所以状态为Listed，然而Bukkit版本是没有的，添加语言文件可能会比较耗时，会在后面的版本中慢慢添加

**Comment by SuoHouDaiShi** [comment]
o
