### ISSUE TITLE
[建议] 对项目文件进行整理

### ISSUE THREAD

**Issue by Silvigarabis** [CSneko/toNeko#42]
您的项目当中包含了针对于不同平台的代码，然而构建时使用的是相同的逻辑，并且各类文件也存放在相同的目录下。

考虑编写构建脚本对多平台构建提供支持，并将代码放在不同的目录下？

**Comment by CSneko** [comment]
将多个版本打包在一起更多的是我的个人习惯导致的，因此我为它写了一套通用的构建脚本，将多个版本的源代码进行拆分能够更好的理清项目结构，不过在开发初期（目前处于重构阶段）将多个版本源代码放在一起开发会更为方便，主要功能完成后会考虑进行拆分，感谢您的建议
