### ISSUE TITLE
使用/toneko player 显示不是猫娘喵~

### ISSUE THREAD

**Issue by xfyqs** [CSneko/toNeko#49]
现在不知道该怎么做喵，就是用不了呜呜唔
![0f9dc9810092ec7b28cc602e2f4a79ef](https://github.com/user-attachments/assets/b92dc74c-5f2a-42b4-80fd-e663ceb9378d)

**Comment by xfyqs** [comment]
知道了，原来要猫娘药水鸭……

**Comment by xfyqs** [comment]
哎呀不对不对，介个是另一个模组的呜呜唔

**Comment by xfyqs** [comment]
哎呀坏了到底是不是啊呜呜唔

**Comment by xfyqs** [comment]
哎呀不行不行，命令一点回馈都没有了呜呜唔

**Comment by CSneko** [comment]
得用猫娘药水哦，当然啦，也可以用/tonekoadmin命令

**Comment by xfyqs** [comment]
> 得用猫娘药水哦，当然啦，也可以用/tonekoadmin命令

哦哦，好哒，谢谢喵
