### ISSUE TITLE
[bug]无法运行

### ISSUE THREAD

**Issue by ChenXi250** [CSneko/toNeko#58]
==================== Basic Information ====================
FCL Version: 1.1.7.8
Architecture: arm64
Android SDK: 34
Java Version: 21
Renderer: Holy-GL4ES
Summarize: Application error, unable to launch, exit code = 1
==================== Basic Information ====================

invoke redirectStdio
invoke setLogPipeReady
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_loader.c:130
Log pipe ready.
invoke setFCLNativeWindow
invoke setEventPipe
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_bridge.c:60
setFCLNativeWindow : 0x7d3ab69aa0, size : 2696x1260
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_event.c:193
Succeeded to set event pipe
==================== Start Minecraft ====================
Device: PD2302
Architecture: arm64
CPU:mt6985
Android SDK: 34
==================== Env Map ====================
Env: PATH=/data/user/0/com.tungsten.fcl/app_runtime/java/jre21/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Env: LIBGL_NOINTOVLHACK=1
Env: JAVA_HOME=/data/user/0/com.tungsten.fcl/app_runtime/java/jre21
Env: LIBGL_NAME=libgl4es_114.so
Env: LIBGL_STRING=Holy-GL4ES
Env: LIBGL_MIPMAP=3
Env: VULKAN_DRIVER_SYSTEM=1
Env: TMPDIR=/data/user/0/com.tungsten.fcl/cache
Env: LIBGL_ES=2
Env: LIBEGL_NAME=libEGL.so
Env: FCL_NATIVEDIR=/data/app/~~CctOMxhDD2OTvuWAxUDoIg==/com.tungsten.fcl-c4B4VGxFSiDu8AQTfzSx4Q==/lib/arm64
Env: LD_LIBRARY_PATH=/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~CctOMxhDD2OTvuWAxUDoIg==/com.tungsten.fcl-c4B4VGxFSiDu8AQTfzSx4Q==/lib/arm64
Env: LIBGL_NOERROR=1
Env: LIBGL_VSYNC=1
Env: HOME=/storage/emulated/0/FCL/log
Env: LIBGL_NORMALIZE=1
==================== Env Map ====================
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 32768
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
glXMakeCurrent FBO workaround enabled
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
Working directory: /storage/emulated/0/FCL/.minecraft/versions/1.21.1
==================== Minecraft Arguments ====================
Java argument: /data/user/0/com.tungsten.fcl/app_runtime/java/jre21/bin/java
Java argument: -Djava.awt.headless=false
Java argument: -Dcacio.managed.screensize=2726x1260
Java argument: -Dcacio.font.fontmanager=sun.awt.X11FontManager
Java argument: -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler
Java argument: -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel
Java argument: -Dawt.toolkit=com.github.caciocavallosilano.cacio.ctc.CTCToolkit
Java argument: -Djava.awt.graphicsenv=com.github.caciocavallosilano.cacio.ctc.CTCGraphicsEnvironment
Java argument: -Djava.system.class.loader=com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader
Java argument: --add-exports=java.desktop/java.awt=ALL-UNNAMED
Java argument: --add-exports=java.desktop/java.awt.peer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.java2d=ALL-UNNAMED
Java argument: --add-exports=java.desktop/java.awt.dnd.peer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.event=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.datatransfer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.font=ALL-UNNAMED
Java argument: --add-exports=java.base/sun.security.action=ALL-UNNAMED
Java argument: --add-opens=java.base/java.util=ALL-UNNAMED
Java argument: --add-opens=java.desktop/java.awt=ALL-UNNAMED
Java argument: --add-opens=java.desktop/sun.font=ALL-UNNAMED
Java argument: --add-opens=java.desktop/sun.java2d=ALL-UNNAMED
Java argument: --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
Java argument: --add-opens=java.base/java.net=ALL-UNNAMED
Java argument: -Xbootclasspath/a:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
Java argument: -Xmx2068m
Java argument: -Dfile.encoding=UTF-8
Java argument: -Dsun.stdout.encoding=UTF-8
Java argument: -Dsun.stderr.encoding=UTF-8
Java argument: -Djava.rmi.server.useCodebaseOnly=true
Java argument: -Dcom.sun.jndi.rmi.object.trustURLCodebase=false
Java argument: -Dcom.sun.jndi.cosnaming.object.trustURLCodebase=false
Java argument: -Dlog4j2.formatMsgNoLookups=true
Java argument: -Dlog4j.configurationFile=/storage/emulated/0/FCL/.minecraft/versions/1.21.1/log4j2.xml
Java argument: -Dminecraft.client.jar=/storage/emulated/0/FCL/.minecraft/versions/1.21.1/1.21.1.jar
Java argument: -Dfml.ignoreInvalidMinecraftCertificates=true
Java argument: -Dfml.ignorePatchDiscrepancies=true
Java argument: -Dext.net.resolvPath=/data/user/0/com.tungsten.fcl/app_runtime/java/jre21/resolv.conf
Java argument: -Djava.io.tmpdir=/data/user/0/com.tungsten.fcl/cache/fclauncher
Java argument: -Dos.name=Linux
Java argument: -Dos.version=Android-14
Java argument: -Dorg.lwjgl.opengl.libname=libgl4es_114.so
Java argument: -Dfml.earlyprogresswindow=false
Java argument: -Dwindow.width=2726
Java argument: -Dwindow.height=1260
Java argument: -Duser.home=/storage/emulated/0/FCL/.minecraft
Java argument: -Duser.language=zh
Java argument: -Duser.timezone=Asia/Shanghai
Java argument: -Dorg.lwjgl.vulkan.libname=libvulkan.so
Java argument: -Djna.boot.library.path=/data/user/0/com.tungsten.fcl/app_runtime/jna/5.14.0
Java argument: -Djava.library.path=/data/user/0/com.tungsten.fcl/app_runtime/java/jre21/lib:/data/user/0/com.tungsten.fcl/app_runtime/java/jre21/lib/jli:/data/user/0/com.tungsten.fcl/app_runtime/java/jre21/lib/server:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/user/0/com.tungsten.fcl/app_runtime/jna:/data/app/~~CctOMxhDD2OTvuWAxUDoIg==/com.tungsten.fcl-c4B4VGxFSiDu8AQTfzSx4Q==/lib/arm64
Java argument: -Djna.tmpdir=/data/user/0/com.tungsten.fcl/cache/fclauncher
Java argument: -Dorg.lwjgl.system.SharedLibraryExtractPath=/data/user/0/com.tungsten.fcl/cache/fclauncher
Java argument: -Dio.netty.native.workdir=/data/user/0/com.tungsten.fcl/cache/fclauncher
Java argument: -Dminecraft.launcher.brand=Fold Craft Launcher
Java argument: -Dminecraft.launcher.version=1.1.7.8
Java argument: -cp
Java argument: /data/user/0/com.tungsten.fcl/app_runtime/lwjgl/lwjgl.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/fabricmc/sponge-mixin/0.15.3+mixin.0.8.7/sponge-mixin-0.15.3+mixin.0.8.7.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/fabricmc/intermediary/1.21.1/intermediary-1.21.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/fabricmc/fabric-loader/0.16.5/fabric-loader-0.16.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/authlib/6.0.54/authlib-6.0.54.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/brigadier/1.3.10/brigadier-1.3.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/datafixerupper/8.0.16/datafixerupper-8.0.16.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/logging/1.2.7/logging-1.2.7.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.22.1/log4j-slf4j2-impl-2.22.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar:/data/user/0/com.tungsten.fcl/files/plugins/MioLaunchWrapper.jar:/storage/emulated/0/FCL/.minecraft/versions/1.21.1/1.21.1.jar
Java argument: --add-exports
Java argument: net.fabricmc.loader.impl.launch.knot/net.fabricmc.loader.impl.launch.knot=ALL-UNNAMED
MainClass: mio.Wrapper
MainClass: net.fabricmc.loader.impl.launch.knot.KnotClient
Minecraft argument: --username
Minecraft argument: ChenXi2010
Minecraft argument: --version
Minecraft argument: 1.21.1
Minecraft argument: --gameDir
Minecraft argument: /storage/emulated/0/FCL/.minecraft/versions/1.21.1
Minecraft argument: --assetsDir
Minecraft argument: /storage/emulated/0/FCL/.minecraft/assets
Minecraft argument: --assetIndex
Minecraft argument: 17
Minecraft argument: --uuid
Minecraft argument: 9feedb2806984581b3cae5186f374a0f
Minecraft argument: --accessToken
Minecraft argument: ***
Minecraft argument: --clientId
Minecraft argument: ${clientid}
Minecraft argument: --xuid
Minecraft argument: ${auth_xuid}
Minecraft argument: --userType
Minecraft argument: msa
Minecraft argument: --versionType
Minecraft argument: Fold Craft Launcher
Minecraft argument: --width
Minecraft argument: 2726
Minecraft argument: --height
Minecraft argument: 1260
Hook success
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/jre_launcher.c:199
Done processing args
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/jre_launcher.c:95
Found JLI lib
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/jre_launcher.c:107
Calling JLI_Launch
[07:10:28] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.5
[07:10:28] [main/WARN]: Mod resolution failed
[07:10:28] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED toneko 1.3.1 {depends minecraft @ [1.21]}, ROOT_FORCELOAD_SINGLE toneko 1.3.1]
[07:10:28] [main/INFO]: Reason: [HARD_DEP toneko 1.3.1 {depends minecraft @ [1.21]}]
[07:10:28] [main/INFO]: Fix: add [], remove [], replace [[minecraft 1.21.1] -> add:minecraft 1.21 ([[1.21,1.21]])]
[07:10:29] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'Minecraft' (minecraft) 1.21.1 with version 1.21.
More details:
	 - Mod 'toNeko' (toneko) 1.3.1 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at mio.Wrapper.main(Wrapper.java:21) [MioLaunchWrapper.jar:?]
[07:10:29] [main/WARN]: Failed to open the error gui!
java.lang.reflect.InvocationTargetException: null
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source) ~[?:?]
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.open0(FabricMainWindow.java:94) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.open(FabricMainWindow.java:88) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.open(FabricGuiEntry.java:51) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.displayError(FabricGuiEntry.java:141) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.displayError(FabricGuiEntry.java:108) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.FabricLauncherBase.handleFormattedException(FabricLauncherBase.java:86) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at mio.Wrapper.main(Wrapper.java:21) [MioLaunchWrapper.jar:?]
Caused by: java.awt.HeadlessException
	at java.desktop/sun.java2d.HeadlessGraphicsEnvironment.getDefaultScreenDevice(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Window.initGC(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Window.init(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Window.<init>(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Frame.<init>(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Frame.<init>(Unknown Source) ~[?:?]
	at java.desktop/javax.swing.JFrame.<init>(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.createUi(FabricMainWindow.java:104) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.lambda$open0$0(FabricMainWindow.java:95) ~[fabric-loader-0.16.5.jar:?]
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source) ~[?:?]
OpenJDK exited with code : 1

**Comment by CSneko** [comment]
更新到[V1.3.2](https://modrinth.com/mod/tonekomod/versions)即可
