### ISSUE TITLE
[可能是bug]部分指令无法使用

### ISSUE THREAD

**Issue by lyy1254** [CSneko/toNeko#62]
我的世界版本：1.20.1（fabric)
toneko版本：1.3.10
前置模组齐全，且除了ctlib,geckolib和钠以外没有其他模组
不知道是不是设备原因，反正就是有些指令用不了
详情看下面这些
![屏幕截图 2024-11-02 135028](https://github.com/user-attachments/assets/5d0d90c5-7ee7-43bf-910d-dba1f5c62d9d)
[latest.log](https://github.com/user-attachments/files/17605861/latest.log)

**Comment by CSneko** [comment]
1.20版本很多东西其实并没有移植过去，目前主要开发版本是1.21，所以呢1.20可能会有很多东西不支持

**Comment by lyy1254** [comment]
谢谢作者大大的解答喵
