### ISSUE TITLE
配置文件无效 版本1.3.10

### ISSUE THREAD

**Issue by M4SOPMODII** [CSneko/toNeko#63]
无论是单人游戏还是服务器，在禁用聊天修改时我发现这不起作用
![Uploading 20241118-35954.png…]()
![20241118-40101](https://github.com/user-attachments/assets/c103e852-cf79-4c02-b663-bae3be3408b9)

**Comment by M4SOPMODII** [comment]
补充一下是在fabric的1.20.1

**Comment by CSneko** [comment]
明白，会修的 (^_^)

**Comment by M4SOPMODII** [comment]
好的多谢

**Comment by CSneko** [comment]
已经修复 https://modrinth.com/mod/tonekomod/version/1.3.11
