### ISSUE TITLE
在配置文里把修改聊天改成否，还是会造成聊天重复

### ISSUE THREAD

**Issue by yunqing-afeng** [CSneko/toNeko#66]
toNeko: 插件版 0.4.5
mohist1.20.1
另外作者有没有兴趣给插件版多加几个功能，比如坐下之类的()

**Comment by CSneko** [comment]
插件版的0.x已经不再更新了哦，可以从Modrinth下载较新的1.x 

对于插件版的新东西呢... 可能会更新的比较慢，目前咱主要是在模组端开发，插件端的同步的话得到咱有时间再说

**Comment by yunqing-afeng** [comment]
我看Modrinth里面的1.x不支持1.20.1呢，想用但是没法用呀

**Comment by CSneko** [comment]
你可以试试呢，我虽然没在1.20.1测试过，不过插件的兼容性一般没这么差呢

**Comment by yunqing-afeng** [comment]
很可惜，1.x用不了
